#!/bin/sh

# Copyright © 2010-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e

if [ $# -eq 0 ]
then
    printf 'Usage: %s <filename>...\n' "$0" >&2
    printf 'Convert audio files to the M4A format.\n\n' >&2
    exit 1
fi

for file in "$@"
do
    ffmpeg -i "$file" -vn -acodec copy -map 0:a -map_metadata 0 "${file%.*}.m4a"
done

# vim:ts=4 sts=4 sw=4 et
