#!/usr/bin/env python3

# Copyright © 2010-2017 Jakub Wilk <jwilk@jwilk.net>
#
# SPDX-License-Identifier: MIT

import argparse
import sys

from mutagen.id3 import ID3

ap = argparse.ArgumentParser(description='change encoding of ID3v2 tags to UCS-2')
ap.add_argument('files', nargs='+', metavar='<filename>')
options = ap.parse_args()

for filename in options.files:
    mp3 = ID3(filename)
    dirty = False
    for key, value in mp3.items():
        if value.encoding == 0:
            continue
        text = str(value)
        try:
            text.encode('ASCII')
            encoding = 0
        except UnicodeError:
            encoding = 1
        value = type(value)(encoding=encoding, text=text)
        mp3[key] = value
        dirty = True
    if dirty:
        print('Writing {path}'.format(path=filename), file=sys.stderr)
        mp3.save()
    else:
        print('Skipping {path}'.format(path=filename), file=sys.stderr)

# vim:ts=4 sts=4 sw=4 et
