#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2010, 2011 Jakub Wilk <jwilk@jwilk.net>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

from __future__ import print_function

import sys
from mutagen.id3 import ID3

if len(sys.argv) < 2:
    print('Usage: %s <filename>' % sys.argv[0], file=sys.stderr)
    print('Change encoding of ID3v2 tags to UCS-2.', file=sys.stderr)
    print(file=sys.stderr)
    sys.exit(1)

for filename in sys.argv[1:]:
    mp3 = ID3(filename)
    dirty = False
    for key, value in mp3.iteritems():
        if value.encoding == 0:
            continue
        text = unicode(value)
        try:
            text = text.decode('ASCII')
            encoding = 0
        except (UnicodeDecodeError, UnicodeEncodeError):
            encoding = 1
        value = type(value)(encoding=encoding, text=text)
        mp3[key] = value
        dirty = True
    if dirty:
        print('Writing %s' % filename, file=sys.stderr)
        mp3.save()
    else:
        print('Skipping %s' % filename, file=sys.stderr)

# vim:ts=4 sts=4 sw=4 et
